/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miprimeraaplicacioncs.Formularios;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import miprimeraaplicacioncs.EmpleadoBeans;

/**
 *
 * @author Usuario
 */
public final class FrmEmpleadosC extends javax.swing.JFrame {

    private EmpleadoBeans empleadoBeans;

    /**
     * Creates new form FrmEmpleadosC
     */
    public FrmEmpleadosC() {
        initComponents();
        try {
            empleadoBeans = new EmpleadoBeans();
            cargarComboIdEmpleados();
            cargarComboCargo();
            cargarComboHorario();
            mostrarDatosEmpleadoSeleccionado();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar el formulario: " + e.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblcedula_ruc = new javax.swing.JLabel();
        txtcedularuc = new javax.swing.JTextField();
        lblnombres = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        lbltelefono = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        cbid = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtEmpleado = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        lbltelefono2 = new javax.swing.JLabel();
        cbidcargo = new javax.swing.JComboBox<>();
        txtcargo = new javax.swing.JTextField();
        lbltelefono1 = new javax.swing.JLabel();
        cbidhorario = new javax.swing.JComboBox<>();
        txthorai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txthoraf = new javax.swing.JTextField();
        txtsueldo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Regresar = new javax.swing.JMenuItem();
        MenuP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Empleado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 170, 40));

        lblcedula_ruc.setText("Cedula_Ruc");
        jPanel1.add(lblcedula_ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 20));
        jPanel1.add(txtcedularuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 170, 20));

        lblnombres.setText("Nombres");
        jPanel1.add(lblnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 50, 20));
        jPanel1.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 170, -1));
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 200, -1));

        lbltelefono.setText("Telefono");
        jPanel1.add(lbltelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 60, 20));

        lbldireccion.setText("Direccion");
        jPanel1.add(lbldireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 60, 20));
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 200, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        cbid.setEditable(true);
        cbid.setPreferredSize(new java.awt.Dimension(55, 25));
        cbid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbidActionPerformed(evt);
            }
        });
        jPanel1.add(cbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 30, -1));

        jtEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "idCargo", "idHorario", "Cedula", "Nombres", "Telefono", "Direccion"
            }
        ));
        jtEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtEmpleado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 710, 100));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        lbltelefono2.setText("Cargo");
        jPanel1.add(lbltelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 50, 20));

        cbidcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbidcargoActionPerformed(evt);
            }
        });
        jPanel1.add(cbidcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, -1));

        txtcargo.setEditable(false);
        jPanel1.add(txtcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 130, -1));

        lbltelefono1.setText("Horario");
        jPanel1.add(lbltelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 50, 20));

        cbidhorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbidhorarioActionPerformed(evt);
            }
        });
        jPanel1.add(cbidhorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, 20));

        txthorai.setEditable(false);
        jPanel1.add(txthorai, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 70, 20));

        jLabel4.setText("Hora Inicio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, 20));

        jLabel5.setText("Hora Fin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, 20));

        txthoraf.setEditable(false);
        jPanel1.add(txthoraf, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 70, 20));

        txtsueldo.setEditable(false);
        jPanel1.add(txtsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 50, -1));

        jLabel6.setText("Sueldo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 40, 20));

        jLabel7.setText("$");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 10, -1));

        jMenu1.setText("Menu");

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jMenu1.add(Regresar);

        MenuP.setText("MenuPrincipal");
        MenuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPActionPerformed(evt);
            }
        });
        jMenu1.add(MenuP);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEmpleadoMouseClicked
        // TODO add your handling code here:
        this.MouseClick();

    }//GEN-LAST:event_jtEmpleadoMouseClicked

    private void cbidcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbidcargoActionPerformed
        // TODO add your handling code here:
        try {
            String cargoId = cbidcargo.getSelectedItem().toString();
            ResultSet rs = empleadoBeans.consultaTabla("SELECT cargo, sueldo FROM cargo WHERE id_cargo = " + cargoId);
            if (rs.next()) {
                txtcargo.setText(rs.getString("cargo"));
                txtsueldo.setText(String.valueOf(rs.getDouble("sueldo")));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al obtener el cargo: " + e.toString());
        }
    }//GEN-LAST:event_cbidcargoActionPerformed

    private void cbidhorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbidhorarioActionPerformed
        // TODO add your handling code here:
        try {
            String horarioId = cbidhorario.getSelectedItem().toString();
            ResultSet rs = empleadoBeans.consultaTabla("SELECT horaInicio, horaFin FROM horario WHERE id_horario = " + horarioId);
            if (rs.next()) {
                txthorai.setText(rs.getString("horaInicio"));
                txthoraf.setText(rs.getString("horaFin"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al obtener el horario: " + e.toString());
        }
    }//GEN-LAST:event_cbidhorarioActionPerformed

    private void cbidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbidActionPerformed
        // TODO add your handling code here:
        mostrarDatosEmpleadoSeleccionado();
    }//GEN-LAST:event_cbidActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        this.Actualizar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        this.Eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        FrmEmpleado fm = new FrmEmpleado();
        this.setVisible(false);
        fm.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    private void MenuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPActionPerformed
        // TODO add your handling code here:
        FrmMenu fm = new FrmMenu();
        this.setVisible(false);
        fm.setVisible(true);
    }//GEN-LAST:event_MenuPActionPerformed

    public void cargarComboIdEmpleados() {
        try {
            ResultSet rs = empleadoBeans.consultaTabla("SELECT id_empleado FROM empleado");
            while (rs.next()) {
                cbid.addItem(rs.getString("id_empleado"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar las IDs de empleados: " + e.toString());
        }
    }

    public void mostrarDatosEmpleadoSeleccionado() {
        try {
            String empleadoId = cbid.getSelectedItem().toString();
            ResultSet rs = empleadoBeans.consultaTabla("SELECT * FROM empleado WHERE id_empleado = " + empleadoId);
            DefaultTableModel modelo = (DefaultTableModel) jtEmpleado.getModel();
            modelo.setRowCount(0);
            while (rs.next()) {
                Object[] fila = {rs.getInt("id_empleado"), rs.getInt("id_cargo"), rs.getInt("id_horario"), rs.getString("cedula"), rs.getString("nombres"), rs.getString("telefono"), rs.getString("direccion")};
                modelo.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al obtener los datos del empleado: " + e.toString());
        }
    }

    private void cargarComboCargo() {
        try {
            ResultSet rs = empleadoBeans.consultaTabla("SELECT * FROM cargo");
            while (rs.next()) {
                cbidcargo.addItem(rs.getString("id_cargo"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los cargos: " + e.toString());
        }
    }

    private void cargarComboHorario() {
        try {
            ResultSet rs = empleadoBeans.consultaTabla("SELECT * FROM horario");
            while (rs.next()) {
                cbidhorario.addItem(rs.getString("id_horario"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los horarios: " + e.toString());
        }
    }

    private void mostrar(javax.swing.JTable jt, String sql) {
        try {
            EmpleadoBeans cb = new EmpleadoBeans();
            ResultSet rs;
            DefaultTableModel modelo = new DefaultTableModel();
            jt.setModel(modelo);
            rs = cb.consultaTabla(sql);
            ResultSetMetaData rsMd;
            rsMd = rs.getMetaData();
            int cantcolumnas = rsMd.getColumnCount();
            for (int i = 1; i <= cantcolumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (rs.next()) {
                Object[] columna = new Object[cantcolumnas];
                for (int i = 0; i < cantcolumnas; i++) {
                    columna[i] = rs.getObject(i + 1);
                }
                modelo.addRow(columna);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }
    }

    private void MouseClick() {
        int fila = jtEmpleado.getSelectedRow();
        cbid.setSelectedItem(jtEmpleado.getModel().getValueAt(fila, 0).toString());
        cbidcargo.setSelectedItem(jtEmpleado.getModel().getValueAt(fila, 1).toString());
        cbidhorario.setSelectedItem(jtEmpleado.getModel().getValueAt(fila, 2).toString());
        txtcedularuc.setText(jtEmpleado.getModel().getValueAt(fila, 3).toString());
        txtnombres.setText(jtEmpleado.getModel().getValueAt(fila, 4).toString());
        txttelefono.setText(jtEmpleado.getModel().getValueAt(fila, 5).toString());
        txtdireccion.setText(jtEmpleado.getModel().getValueAt(fila, 6).toString());
    }

    public void Actualizar() {
        try {
            EmpleadoBeans cb = new EmpleadoBeans();
            cb.setId_Empleado(Integer.parseInt(cbid.getSelectedItem().toString()));
            cb.setId_cargo(Integer.parseInt(cbidcargo.getSelectedItem().toString()));
            cb.setId_horario(Integer.parseInt(cbidhorario.getSelectedItem().toString()));
            cb.setCedula(txtcedularuc.getText());
            cb.setNombres(txtnombres.getText());
            cb.setTelefono(txttelefono.getText());
            cb.setDireccion(txtdireccion.getText());
            cb.Actualizar_Empleado();
            this.mostrar(jtEmpleado, "SELECT * FROM empleado WHERE id_empleado = " + cb.getId_Empleado());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el empleado: " + e.toString());
        }
    }

    public void Eliminar() {
        try {
            EmpleadoBeans cb = new EmpleadoBeans();
            cb.setId_Empleado(Integer.parseInt(cbid.getSelectedItem().toString()));
            cb.Eliminar_Empleado();
            this.mostrar(jtEmpleado, "SELECT * FROM empleado WHERE id_empleado = " + cb.getId_Empleado());
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuP;
    private javax.swing.JMenuItem Regresar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbid;
    private javax.swing.JComboBox<String> cbidcargo;
    private javax.swing.JComboBox<String> cbidhorario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtEmpleado;
    private javax.swing.JLabel lblcedula_ruc;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JLabel lbltelefono1;
    private javax.swing.JLabel lbltelefono2;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtcedularuc;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txthoraf;
    private javax.swing.JTextField txthorai;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtsueldo;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
