/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miprimeraaplicacioncs.Formularios;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import miprimeraaplicacioncs.FacturaBeans;
import miprimeraaplicacioncs.RegistrarBeans;

/**
 *
 * @author Usuario
 */
public class FrmFactura extends javax.swing.JFrame {

    private final RegistrarBeans registroBeans;

    /**
     * Creates new form FrmFactura
     *
     * @throws java.lang.Exception
     */
    public FrmFactura() throws Exception {
        initComponents();
        registroBeans = new RegistrarBeans();
        cargarRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtidfactura = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbidregistro = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        txtmetodo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtpago = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFactura = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtmetodopago = new javax.swing.JTextField();
        txtNcliente = new javax.swing.JTextField();
        txtruc = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        txtfechai = new javax.swing.JTextField();
        txtfechaf = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtpiso = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtdesc = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtiva = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtdescuento = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txttotaliva = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtpaga = new javax.swing.JTextField();
        txtsaldo = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Regresar = new javax.swing.JMenuItem();
        MenuP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("FACTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 40));

        btnNuevo.setText("Nueva Factura");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 30));

        jLabel9.setText("Factura N°");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 60, 30));
        jPanel1.add(txtidfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 40, 30));

        jLabel10.setText("Registro ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 30));

        cbidregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbidregistroActionPerformed(evt);
            }
        });
        jPanel1.add(cbidregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, 30));

        jLabel8.setText("Clliente");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, 30));

        txtcliente.setEditable(false);
        jPanel1.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 270, 30));

        txtmetodo.setEditable(false);
        jPanel1.add(txtmetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 110, 30));

        jLabel11.setText("Metodo de Pago");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 80, 30));

        txtcedula.setEditable(false);
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 220, 30));

        jLabel12.setText("Cedula_Ruc");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 70, 30));

        jLabel15.setText("%");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 20, 30));

        txtpago.setEditable(false);
        txtpago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpagoKeyReleased(evt);
            }
        });
        jPanel1.add(txtpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 90, 30));

        jLabel16.setText("Pagó");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 40, 30));

        jLabel3.setText("Informacion Cliente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 720, 110));

        jtFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° Factura", "Cliente", "N\" Habitacion", "Precio", "Pago"
            }
        ));
        jtFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFacturaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFactura);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 720, 60));

        jLabel4.setText("Cliente");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 40, 20));

        jLabel5.setText("Cedula");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 40, 20));

        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 20));

        jLabel7.setText("N° Habitacion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 20));

        jLabel13.setText("Fecha Fin");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 60, 20));

        jLabel14.setText("Fecha Inicio");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 20));

        jLabel17.setText("Metodo de Pago");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 20));

        txtmetodopago.setEditable(false);
        jPanel1.add(txtmetodopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 170, -1));

        txtNcliente.setEditable(false);
        jPanel1.add(txtNcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 170, -1));

        txtruc.setEditable(false);
        jPanel1.add(txtruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 170, -1));

        txttelefono.setEditable(false);
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 170, -1));

        txtnumero.setEditable(false);
        jPanel1.add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 70, -1));

        txtfechai.setEditable(false);
        jPanel1.add(txtfechai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 170, -1));

        txtfechaf.setEditable(false);
        jPanel1.add(txtfechaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 170, -1));

        jLabel35.setText("Piso");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 30, 20));

        txtpiso.setEditable(false);
        jPanel1.add(txtpiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 60, -1));

        jLabel19.setText("Informacion de la Factura");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 300, 200));

        jLabel20.setText("Descuento");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 60, 30));

        txtdesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdescKeyReleased(evt);
            }
        });
        jPanel1.add(txtdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 30, 30));

        jLabel21.setText("$");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 20, 30));

        jLabel22.setText("Precio de la Habitacion");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 120, 30));

        txtprecio.setEditable(false);
        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprecioKeyReleased(evt);
            }
        });
        jPanel1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 40, 30));

        jLabel23.setText("$");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 20, 30));

        jLabel24.setText("Iva");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 60, 30));

        txtiva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtivaKeyReleased(evt);
            }
        });
        jPanel1.add(txtiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 30, 30));

        jLabel25.setText("%");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 20, 30));

        jLabel26.setText("$");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 20, 30));

        txtdescuento.setEditable(false);
        txtdescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdescuentoKeyReleased(evt);
            }
        });
        jPanel1.add(txtdescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 40, 30));

        jLabel27.setText("$");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 20, 30));

        txttotaliva.setEditable(false);
        txttotaliva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttotalivaKeyReleased(evt);
            }
        });
        jPanel1.add(txttotaliva, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 40, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Total de la Factura");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 120, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("$");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 20, 30));

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 40, 30));

        jLabel30.setText("Pago");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 50, 30));

        jLabel31.setText("$");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 20, 30));

        txtpaga.setEditable(false);
        jPanel1.add(txtpaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 50, 30));

        txtsaldo.setEditable(false);
        jPanel1.add(txtsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 50, 30));

        jLabel32.setText("$");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 20, 30));

        jLabel33.setText("Saldo");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 50, 30));

        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 160, 100));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jMenu1.setText("Menu");

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jMenu1.add(Regresar);

        MenuP.setText("Menu Principal");
        MenuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPActionPerformed(evt);
            }
        });
        jMenu1.add(MenuP);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbidregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbidregistroActionPerformed
        // TODO add your handling code here:
        try {
            String registro = cbidregistro.getSelectedItem().toString();
            ResultSet rs = registroBeans.consultaTabla("SELECT r.metodo, r.pago, r.fechaInicio, r.fechaFin, c.apellidos, c.cedula, c.telefono, h.numero, h.piso, h.precio FROM registros r JOIN cliente c ON r.id_cliente = c.id_cliente JOIN habitaciones h ON r.id_habitacion = h.id_habitacion WHERE r.id_registro = '" + registro + "'");
            if (rs.next()) {
                txtmetodo.setText(rs.getString("metodo"));
                txtmetodopago.setText(rs.getString("metodo"));
                txtcliente.setText(rs.getString("apellidos"));
                txtNcliente.setText(rs.getString("apellidos"));
                txtcedula.setText(rs.getString("cedula"));
                txtruc.setText(rs.getString("cedula"));
                txttelefono.setText(rs.getString("telefono"));
                txtnumero.setText(rs.getString("numero"));
                txtpiso.setText(rs.getString("piso"));
                txtfechai.setText(rs.getString("fechaInicio"));
                txtfechaf.setText(rs.getString("fechaFin"));
                txtpago.setText(rs.getString("pago"));
                txtpaga.setText(rs.getString("pago"));
                txtprecio.setText(rs.getString("precio"));

            }
        } catch (SQLException e) {
            System.out.println("Error al obtener el registros: " + e.toString());
        }
    }//GEN-LAST:event_cbidregistroActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        this.enviar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jtFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFacturaMouseClicked
        // TODO add your handling code here:
        this.MouseClick();
    }//GEN-LAST:event_jtFacturaMouseClicked

    private void txtprecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtprecioKeyReleased

    private void txtdescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescuentoKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtdescuentoKeyReleased

    private void txttotalivaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalivaKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txttotalivaKeyReleased

    private void txtdescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescKeyReleased
        // TODO add your handling code here:
        calcularTotal();
    }//GEN-LAST:event_txtdescKeyReleased

    private void txtivaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtivaKeyReleased
        // TODO add your handling code here:
        calcularTotal();
    }//GEN-LAST:event_txtivaKeyReleased

    private void txtpagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpagoKeyReleased
        // TODO add your handling code here:
        calcularTotal();
    }//GEN-LAST:event_txtpagoKeyReleased

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        try {
            // TODO add your handling code here:
            FrmRegistrar fr = new FrmRegistrar();
            this.setVisible(false);
            fr.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RegresarActionPerformed

    private void MenuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPActionPerformed
        // TODO add your handling code here:
        FrmMenu fr = new FrmMenu();
        this.setVisible(false);
        fr.setVisible(true);
    }//GEN-LAST:event_MenuPActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        this.imprimirFactura();
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarRegistro() {
        try {
            ResultSet rs = registroBeans.consultaTabla("SELECT * FROM registros");
            while (rs.next()) {
                cbidregistro.addItem(rs.getString("id_registro"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los cargos: " + e.toString());
        }
    }

    private void nuevo() {
        try {
            FacturaBeans cb = new FacturaBeans();
            txtidfactura.setText("" + cb.Incremento_Factura());
            cbidregistro.setSelectedItem("");
            txtdescuento.setText("");
            txttotaliva.setText("");
            txttotal.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error..." + e.toString());
        }
    }

    private void enviar() {
        try {
            FacturaBeans cb = new FacturaBeans();
            cb.setId_Factura(Integer.parseInt(txtidfactura.getText()));
            cb.setId_Registro(Integer.parseInt(cbidregistro.getSelectedItem().toString()));
            cb.setDescuento(Double.parseDouble(txtdescuento.getText()));
            cb.setIva(Double.parseDouble(txttotaliva.getText()));
            cb.setTotal(Double.parseDouble(txttotal.getText()));
            cb.Insertar_Factura();
            this.mostrar(jtFactura, "SELECT f.id_factura, c.apellidos, h.numero, h.precio, r.pago FROM factura f JOIN registros r ON f.id_registro = r.id_registro JOIN cliente c ON r.id_cliente = c.id_cliente JOIN habitaciones h ON r.id_habitacion = h.id_habitacion WHERE f.id_factura ='" + txtidfactura.getText() + "'");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de transaccion RollBack..." + e.toString());
        }
    }

    private void mostrar(javax.swing.JTable JT, String sql) {
        try {
            FacturaBeans cb = new FacturaBeans();
            ResultSet rs;
            DefaultTableModel modelo = new DefaultTableModel();
            JT.setModel(modelo);
            rs = cb.consultaTabla(sql);
            ResultSetMetaData rsMd;
            rsMd = rs.getMetaData();
            int cantcolumnas = rsMd.getColumnCount();
            for (int i = 1; i <= cantcolumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (rs.next()) {
                Object[] columna = new Object[cantcolumnas];
                columna[0] = txtidfactura.getText();
                columna[1] = txtcliente.getText();
                columna[2] = txtnumero.getText();
                columna[3] = txtprecio.getText();
                columna[4] = txtpago.getText();
                modelo.addRow(columna);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }
    }

    private void MouseClick() {
        int fila = jtFactura.getSelectedRow();
        txtidfactura.setText(jtFactura.getModel().getValueAt(fila, 0).toString());
        txtcliente.setText(jtFactura.getModel().getValueAt(fila, 1).toString());
        txtnumero.setText(jtFactura.getModel().getValueAt(fila, 2).toString());
        txtprecio.setText(jtFactura.getModel().getValueAt(fila, 3).toString());
        txtpago.setText(jtFactura.getModel().getValueAt(fila, 4).toString());
    }

    private void calcularTotal() {
        try {
            double precio = Double.parseDouble(txtprecio.getText());
            double descuento = Double.parseDouble(txtdesc.getText());
            double iva = Double.parseDouble(txtiva.getText());

            double totalDescuento = precio * (descuento / 100);
            double totalIva = precio * (iva / 100);
            double total = precio - totalDescuento + totalIva;

            txtdescuento.setText(String.valueOf(totalDescuento));
            txttotaliva.setText(String.valueOf(totalIva));
            txttotal.setText(String.valueOf(total));

            calcularSaldo();
        } catch (NumberFormatException e) {
            // Manejo de errores si los campos no contienen números válidos
        }
    }

    private void calcularSaldo() {
        try {
            double total = Double.parseDouble(txttotal.getText());
            double pago = Double.parseDouble(txtpago.getText());

            double saldo = pago - total;

            txtsaldo.setText(String.valueOf(saldo));
        } catch (NumberFormatException e) {
            // Manejo de errores si los campos no contienen números válidos
        }
    }

    private void imprimirFactura() {
        StringBuilder factura = new StringBuilder();
        factura.append("*********** FACTURA ***********\n");
        factura.append("Cliente: ").append(txtcliente.getText()).append("\n");
        factura.append("Cédula: ").append(txtcedula.getText()).append("\n");
        factura.append("Teléfono: ").append(txttelefono.getText()).append("\n");
        factura.append("N° Habitación: ").append(txtnumero.getText()).append("\n");
        factura.append("Fecha Inicio: ").append(txtfechai.getText()).append("\n");
        factura.append("Fecha Fin: ").append(txtfechaf.getText()).append("\n");
        factura.append("Método de Pago: ").append(txtmetodo.getText()).append("\n");
        factura.append("Precio de la Habitación: $").append(txtprecio.getText()).append("\n");
        factura.append("Descuento: $").append(txtdescuento.getText()).append("\n");
        factura.append("IVA: $").append(txttotaliva.getText()).append("\n");
        factura.append("Total a Pagar: $").append(txttotal.getText()).append("\n");
        factura.append("Pago: $").append(txtpago.getText()).append("\n");
        factura.append("Saldo: $").append(txtsaldo.getText()).append("\n");
        factura.append("******************************");

        JOptionPane.showMessageDialog(this, factura.toString(), "Factura", JOptionPane.INFORMATION_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuP;
    private javax.swing.JMenuItem Regresar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbidregistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtFactura;
    private javax.swing.JTextField txtNcliente;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtdescuento;
    private javax.swing.JTextField txtfechaf;
    private javax.swing.JTextField txtfechai;
    private javax.swing.JTextField txtidfactura;
    private javax.swing.JTextField txtiva;
    private javax.swing.JTextField txtmetodo;
    private javax.swing.JTextField txtmetodopago;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtpaga;
    private javax.swing.JTextField txtpago;
    private javax.swing.JTextField txtpiso;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtruc;
    private javax.swing.JTextField txtsaldo;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotaliva;
    // End of variables declaration//GEN-END:variables
}
