/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miprimeraaplicacioncs.Formularios;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import miprimeraaplicacioncs.HabitacionesBeans;

/**
 *
 * @author Usuario
 */
public final class FrmHabitacion extends javax.swing.JFrame {

    private final HabitacionesBeans habitaciones;

    /**
     * Creates new form FrmHabitacion
     *
     * @throws java.lang.Exception
     */
    public FrmHabitacion() throws Exception {
        initComponents();
        obtenerOpcionesDisponibilidad();
        habitaciones = new HabitacionesBeans();
        cargarComboEmpleado();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtidhabitacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbempleado = new javax.swing.JComboBox<>();
        txtnumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbdisponicilidad = new javax.swing.JComboBox<>();
        txtcedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfechaR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtpiso = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHabitaciones = new javax.swing.JTable();
        txtidempleado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuHa = new javax.swing.JMenuItem();
        MenuP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("INGRESO DE HABITACIONES");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNuevo))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 60));

        jLabel2.setText("ID Habitacion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 30));
        jPanel1.add(txtidhabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 40, 30));

        jLabel3.setText("Numero ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 30));

        cbempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbempleadoActionPerformed(evt);
            }
        });
        jPanel1.add(cbempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 180, 30));
        jPanel1.add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 40, 30));

        jLabel4.setText("C.I.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 30, 30));

        jLabel5.setText("dd/mm/aaaa");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 70, 30));
        jPanel1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 50, 30));

        jLabel6.setText("$");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 10, 20));

        jLabel7.setText("Disponibilidad");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 80, 30));

        jPanel1.add(cbdisponicilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, 30));

        txtcedula.setEditable(false);
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 150, 30));

        jLabel8.setText("Registro Por");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 70, 30));
        jPanel1.add(txtfechaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 130, 30));

        jLabel9.setText("Fecha de Registro");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));
        jPanel1.add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 540, 30));

        jLabel10.setText("Descripcion");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, 30));

        jLabel11.setText("Precio");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 40, 30));

        jLabel12.setText("Piso");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, 30));
        jPanel1.add(txtpiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 40, 30));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        btnEliminar.setText("Elminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jtHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "IdHabitaciones", "Numero", "Precio", "Fecha Registro", "Disponibilidad", "Registrado por"
            }
        ));
        jtHabitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtHabitacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtHabitaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 660, 100));

        txtidempleado.setEditable(false);
        jPanel1.add(txtidempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 30, 30));

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 450, 50));

        jMenu1.setText("Menu");

        MenuHa.setText("Menu Habitaciones");
        MenuHa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuHa);

        MenuP.setText("Menu Principal");
        MenuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPActionPerformed(evt);
            }
        });
        jMenu1.add(MenuP);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        this.enviar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cbempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbempleadoActionPerformed
        // TODO add your handling code here:
        try {
            String empleado = cbempleado.getSelectedItem().toString();
            ResultSet rs = habitaciones.consultaTabla("SELECT id_empleado, cedula FROM empleado WHERE nombres = '" + empleado + "'");
            if (rs.next()) {
                txtidempleado.setText(rs.getString("id_empleado"));
                txtcedula.setText(rs.getString("cedula"));
            }
        } catch (SQLException e) {
            System.out.println("Error al obtener el empleado: " + e.toString());
        }
    }//GEN-LAST:event_cbempleadoActionPerformed

    private void jtHabitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtHabitacionesMouseClicked
        // TODO add your handling code here:
        this.MouseClick();
    }//GEN-LAST:event_jtHabitacionesMouseClicked

    private void MenuHaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHaActionPerformed

        // TODO add your handling code here:
        FrmHabitaciones hb = new FrmHabitaciones();
        this.setVisible(false);
        hb.setVisible(true);

    }//GEN-LAST:event_MenuHaActionPerformed

    private void MenuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPActionPerformed
        // TODO add your handling code here:
        FrmMenu fm = new FrmMenu();
        this.setVisible(false);
        fm.setVisible(true);
    }//GEN-LAST:event_MenuPActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        this.Eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    public void obtenerOpcionesDisponibilidad() {
        cbdisponicilidad.addItem("Si");
        cbdisponicilidad.addItem("No");
    }

    private void cargarComboEmpleado() {
        try {
            ResultSet rs = habitaciones.consultaTabla("SELECT * FROM empleado");
            while (rs.next()) {
                cbempleado.addItem(rs.getString("nombres"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los empleado: " + e.toString());
        }
    }

    private void nuevo() {
        try {
            HabitacionesBeans cb = new HabitacionesBeans();
            txtidhabitacion.setText("" + cb.Incremento_Habitaciones());
            txtidempleado.setText("");
            cbempleado.setSelectedItem("");
            txtnumero.setText("");
            txtpiso.setText("");
            txtprecio.setText("");
            cbdisponicilidad.setSelectedItem("");
            txtfechaR.setText("");
            txtdescripcion.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error..." + e.toString());
        }
    }

    private void enviar() {
        try {
            HabitacionesBeans cb = new HabitacionesBeans();
            cb.setId_Habitacion(Integer.parseInt(txtidhabitacion.getText()));
            cb.setId_Empleado(Integer.parseInt(txtidempleado.getText()));
            cb.setNumero(Integer.parseInt(txtnumero.getText()));
            cb.setPiso(Integer.parseInt(txtpiso.getText()));
            cb.setPrecio(Double.parseDouble(txtprecio.getText()));
            cb.setDisponibilidad(cbdisponicilidad.getSelectedItem().toString());
            cb.setFecha_Registro(txtfechaR.getText());
            cb.setDescipcion(txtdescripcion.getText());
            cb.Insertar_Habitaciones();
            this.mostrar(jtHabitaciones, "SELECT h.id_habitacion, h.numero, h.precio, h.fechaRegistro, h.disponibilidad, e.nombres FROM habitaciones h JOIN empleado e ON h.id_empleado = e.id_empleado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de transacción RollBack..." + e.toString());
        }
    }

    private void mostrar(javax.swing.JTable JT, String sql) {
        try {
            HabitacionesBeans cb = new HabitacionesBeans();
            ResultSet rs;
            DefaultTableModel modelo = new DefaultTableModel();
            JT.setModel(modelo);
            rs = cb.consultaTabla(sql);
            ResultSetMetaData rsMd;
            rsMd = rs.getMetaData();
            int cantcolumnas = rsMd.getColumnCount();
            for (int i = 1; i <= cantcolumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (rs.next()) {
                Object[] columna = new Object[cantcolumnas];
                for (int i = 0; i < cantcolumnas; i++) {
                    columna[i] = rs.getObject(i + 1);
                }
                modelo.addRow(columna);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }
    }

    public void Eliminar() {
        try {
            HabitacionesBeans cb = new HabitacionesBeans();
            cb.setId_Habitacion(Integer.parseInt(txtidhabitacion.getText()));
            cb.Eliminar_Habitaciones();
            this.mostrar(jtHabitaciones, "SELECT h.id_habitacion, h.numero, h.precio, h.fechaRegistro, h.disponibilidad, e.nombres FROM habitaciones h JOIN empleado e ON h.id_empleado = e.id_empleado");
        } catch (Exception e) {
        }
    }

    private void MouseClick() {
        int fila = jtHabitaciones.getSelectedRow();
        txtidhabitacion.setText(jtHabitaciones.getModel().getValueAt(fila, 0).toString());
        txtnumero.setText(jtHabitaciones.getModel().getValueAt(fila, 1).toString());
        txtprecio.setText(jtHabitaciones.getModel().getValueAt(fila, 2).toString());
        txtfechaR.setText(jtHabitaciones.getModel().getValueAt(fila, 3).toString());
        cbdisponicilidad.setSelectedItem(jtHabitaciones.getModel().getValueAt(fila, 4).toString());
        cbempleado.setSelectedItem(jtHabitaciones.getModel().getValueAt(fila, 5).toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuHa;
    private javax.swing.JMenuItem MenuP;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbdisponicilidad;
    private javax.swing.JComboBox<String> cbempleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtHabitaciones;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtfechaR;
    private javax.swing.JTextField txtidempleado;
    private javax.swing.JTextField txtidhabitacion;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtpiso;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
