/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miprimeraaplicacioncs.Formularios;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import miprimeraaplicacioncs.ClienteBeans;
import miprimeraaplicacioncs.HorarioBeans;

/**
 *
 * @author Usuario
 */
public class FrmHorario extends javax.swing.JFrame {

    private HorarioBeans horarioBeans;

    /**
     * Creates new form FrmHorario
     */
    public FrmHorario() throws Exception {
        initComponents();
        horarioBeans = new HorarioBeans();
        cargarIdHorarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtidhorario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txthorai = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txthoraf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rma = new javax.swing.JRadioButton();
        rlu = new javax.swing.JRadioButton();
        rmi = new javax.swing.JRadioButton();
        rju = new javax.swing.JRadioButton();
        rvi = new javax.swing.JRadioButton();
        rsa = new javax.swing.JRadioButton();
        rd = new javax.swing.JRadioButton();
        txtdias = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbid = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHorario = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Regresar = new javax.swing.JMenuItem();
        MenuP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtidhorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 30, 30));

        jLabel9.setText("Id Horario");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 60, 30));

        jLabel10.setText("Hora Inicio");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 60, 30));
        jPanel1.add(txthorai, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 100, 30));

        jLabel11.setText("Hora Fin");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 60, 30));
        jPanel1.add(txthoraf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 100, 30));

        jLabel12.setText("Dias");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 40, 20));

        rma.setText("Ma");
        rma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmaActionPerformed(evt);
            }
        });
        jPanel1.add(rma, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        rlu.setText("Lu");
        rlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rluActionPerformed(evt);
            }
        });
        jPanel1.add(rlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        rmi.setText("Mi");
        rmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmiActionPerformed(evt);
            }
        });
        jPanel1.add(rmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        rju.setText("Ju");
        rju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rjuActionPerformed(evt);
            }
        });
        jPanel1.add(rju, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        rvi.setText("Vi");
        rvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rviActionPerformed(evt);
            }
        });
        jPanel1.add(rvi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        rsa.setText("Sa");
        rsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsaActionPerformed(evt);
            }
        });
        jPanel1.add(rsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        rd.setText("Do");
        rd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdActionPerformed(evt);
            }
        });
        jPanel1.add(rd, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));
        jPanel1.add(txtdias, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 210, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 230, 130));

        btnNuevo.setText("Nuevo Horario");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("HORARIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 70));

        cbid.setEditable(true);
        cbid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbidActionPerformed(evt);
            }
        });
        jPanel1.add(cbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 200, 40, 25));

        jtHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdHorario", "Hora Inicio", "Hora Fin", "Dias"
            }
        ));
        jtHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtHorarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtHorario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 630, 100));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jMenu1.setText("Menu");

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jMenu1.add(Regresar);

        MenuP.setText("Menu Principal");
        MenuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPActionPerformed(evt);
            }
        });
        jMenu1.add(MenuP);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbidActionPerformed
        // TODO add your handling code here:
        try {
            int selectedId = Integer.parseInt(cbid.getSelectedItem().toString());
            horarioBeans.setId_Horario(selectedId);
            mostrar(jtHorario, "SELECT * FROM horario WHERE id_horario = " + selectedId);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }
    }//GEN-LAST:event_cbidActionPerformed

    private void rluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rluActionPerformed
        // TODO add your handling code here:
        setDiasFromRadioButtons();
    }//GEN-LAST:event_rluActionPerformed

    private void rmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmaActionPerformed
        // TODO add your handling code here:
        setDiasFromRadioButtons();
    }//GEN-LAST:event_rmaActionPerformed

    private void rmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmiActionPerformed
        // TODO add your handling code here:
        setDiasFromRadioButtons();
    }//GEN-LAST:event_rmiActionPerformed

    private void rjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rjuActionPerformed
        // TODO add your handling code here:
        setDiasFromRadioButtons();
    }//GEN-LAST:event_rjuActionPerformed

    private void rviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rviActionPerformed
        // TODO add your handling code here:
        setDiasFromRadioButtons();
    }//GEN-LAST:event_rviActionPerformed

    private void rsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsaActionPerformed
        // TODO add your handling code here:
        setDiasFromRadioButtons();
    }//GEN-LAST:event_rsaActionPerformed

    private void rdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdActionPerformed
        // TODO add your handling code here:
        setDiasFromRadioButtons();
    }//GEN-LAST:event_rdActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        this.Eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        this.Actualizar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        this.enviar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jtHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtHorarioMouseClicked
        // TODO add your handling code here:
        this.MouseClick();
    }//GEN-LAST:event_jtHorarioMouseClicked

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        FrmEmpleado fm = new FrmEmpleado();
        this.setVisible(false);
        fm.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    private void MenuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPActionPerformed
        // TODO add your handling code here:
        FrmMenu fm = new FrmMenu();
        this.setVisible(false);
        fm.setVisible(true);
    }//GEN-LAST:event_MenuPActionPerformed

    /**
     * @param args the command line arguments
     */
    private void nuevo() {
        try {
            HorarioBeans hb = new HorarioBeans();
            txtidhorario.setText("" + hb.Incremento_Horario());
            txthorai.setText("");
            txthoraf.setText("");
            txtdias.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error..." + e.toString());
        }
    }

    private void enviar() {
        try {
            int idHorario = Integer.parseInt(txtidhorario.getText());
            String horaInicio = txthorai.getText();
            String horaFin = txthoraf.getText();
            String dias = txtdias.getText();
            horarioBeans.setId_Horario(idHorario);
            horarioBeans.setHora_Inicio(horaInicio);
            horarioBeans.setHora_Fin(horaFin);
            horarioBeans.setDias(dias);
            horarioBeans.Insertar_Horario();
            mostrar(jtHorario, "SELECT * FROM horario");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al enviar el horario: " + e.toString());
        }
    }

    private void mostrar(javax.swing.JTable JT, String sql) {
        try {
            ClienteBeans cb = new ClienteBeans();
            ResultSet rs;
            DefaultTableModel modelo = new DefaultTableModel();
            JT.setModel(modelo);
            rs = cb.consultaTabla(sql);
            ResultSetMetaData rsMd;
            rsMd = rs.getMetaData();
            int cantcolumnas = rsMd.getColumnCount();
            for (int i = 1; i <= cantcolumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (rs.next()) {
                Object[] columna = new Object[cantcolumnas];
                for (int i = 0; i < cantcolumnas; i++) {
                    columna[i] = rs.getObject(i + 1);
                }
                modelo.addRow(columna);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }
    }

    private void cargarIdHorarios() {
        try {
            ResultSet rs = horarioBeans.consultaTabla("SELECT id_horario FROM horario");
            while (rs.next()) {
                cbid.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }
    }

    private void setDiasFromRadioButtons() {
        StringBuilder diasBuilder = new StringBuilder();
        if (rlu.isSelected()) {
            diasBuilder.append("Lu ");
        }
        if (rma.isSelected()) {
            diasBuilder.append("Ma ");
        }
        if (rmi.isSelected()) {
            diasBuilder.append("Mi ");
        }
        if (rju.isSelected()) {
            diasBuilder.append("Ju ");
        }
        if (rvi.isSelected()) {
            diasBuilder.append("Vi ");
        }
        if (rsa.isSelected()) {
            diasBuilder.append("Sa ");
        }
        if (rd.isSelected()) {
            diasBuilder.append("Do");
        }
        txtdias.setText(diasBuilder.toString());
    }

    private void Actualizar() {
        try {
            HorarioBeans cb = new HorarioBeans();
            cb.setId_Horario(Integer.parseInt(txtidhorario.getText()));
            cb.setHora_Inicio(txthorai.getText());
            cb.setHora_Fin(txthoraf.getText());
            cb.setDias(txtdias.getText());
            cb.Actualizar_Horario();
            this.mostrar(jtHorario, "SELECT * FROM horario");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de transaccion RollBack..." + e.toString());
        }
    }

    private void Eliminar() {
        try {
            HorarioBeans cb = new HorarioBeans();
            cb.setId_Horario(Integer.parseInt(txtidhorario.getText()));
            cb.Eliminar_Horario();
            this.mostrar(jtHorario, "SELECT * FROM horario");
        } catch (Exception e) {
        }
    }

    private void MouseClick() {
        int fila = jtHorario.getSelectedRow();
        txtidhorario.setText(jtHorario.getModel().getValueAt(fila, 0).toString());
        txthorai.setText(jtHorario.getModel().getValueAt(fila, 1).toString());
        txthoraf.setText(jtHorario.getModel().getValueAt(fila, 2).toString());
        txtdias.setText(jtHorario.getModel().getValueAt(fila, 3).toString());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuP;
    private javax.swing.JMenuItem Regresar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtHorario;
    private javax.swing.JRadioButton rd;
    private javax.swing.JRadioButton rju;
    private javax.swing.JRadioButton rlu;
    private javax.swing.JRadioButton rma;
    private javax.swing.JRadioButton rmi;
    private javax.swing.JRadioButton rsa;
    private javax.swing.JRadioButton rvi;
    private javax.swing.JTextField txtdias;
    private javax.swing.JTextField txthoraf;
    private javax.swing.JTextField txthorai;
    private javax.swing.JTextField txtidhorario;
    // End of variables declaration//GEN-END:variables
}
