/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miprimeraaplicacioncs.Formularios;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import miprimeraaplicacioncs.ClienteBeans;
import miprimeraaplicacioncs.RegistrarBeans;

/**
 *
 * @author Usuario
 */
public class FrmRegistros extends javax.swing.JFrame {

    private final ClienteBeans clienteBeans;

    /**
     * Creates new form FrmRegistros
     *
     * @throws java.lang.Exception
     */
    public FrmRegistros() throws Exception {
        initComponents();
        clienteBeans = new ClienteBeans();
        cargarCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtRegistro = new javax.swing.JTable();
        btnconsultart = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        cbcedula = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtRegistro.setBorder(new javax.swing.border.MatteBorder(null));
        jtRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Habitacion N°", "Fecha Inicio", "Fecha Fin", "Metodo de Pago", "Pagó", "Registrado Por"
            }
        ));
        jtRegistro.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jtRegistro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1030, 120));

        btnconsultart.setText("Consultar Todos");
        btnconsultart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultartActionPerformed(evt);
            }
        });
        jPanel1.add(btnconsultart, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 120, 30));

        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, 30));

        jLabel2.setText("CEDULA_RUC");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 90, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("CLIENTES REGISTRADOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 40));

        txtid.setEditable(false);
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 30, 30));

        cbcedula.setEditable(true);
        cbcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcedulaActionPerformed(evt);
            }
        });
        jPanel1.add(cbcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 200, 30));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Regresar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Menu Principal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultartActionPerformed
        // TODO add your handling code here:
        this.mostrar(jtRegistro, "SELECT cliente.apellidos, habitaciones.numero, registros.fechaInicio, registros.fechaFin, registros.Metodo, registros.Pago, empleado.nombres FROM cliente, habitaciones, registros, empleado WHERE cliente.id_cliente = registros.id_cliente AND habitaciones.id_habitacion = registros.id_habitacion AND empleado.id_empleado = registros.id_empleado");
    }//GEN-LAST:event_btnconsultartActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
        this.mostrar(jtRegistro, "SELECT cliente.apellidos, habitaciones.numero, registros.fechaInicio, registros.fechaFin, registros.Metodo, registros.Pago, empleado.nombres FROM cliente, habitaciones, registros, empleado WHERE cliente.id_cliente = registros.id_cliente AND habitaciones.id_habitacion = registros.id_habitacion AND empleado.id_empleado = registros.id_empleado AND cliente.id_cliente = '" + txtid.getText() + "'");
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void cbcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcedulaActionPerformed
        // TODO add your handling code here:
        try {
            String cliente = cbcedula.getSelectedItem().toString();
            ResultSet rs = clienteBeans.consultaTabla("SELECT id_cliente FROM cliente WHERE cedula = '" + cliente + "'");
            if (rs.next()) {
                txtid.setText(rs.getString("id_cliente"));
            }
        } catch (SQLException e) {
            System.out.println("Error al obtener el empleado: " + e.toString());
        }
    }//GEN-LAST:event_cbcedulaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            // TODO add your handling code here:
            FrmRegistrar fr = new FrmRegistrar();
            this.setVisible(false);
            fr.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmRegistros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FrmMenu fr = new FrmMenu();
        this.setVisible(false);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void mostrar(javax.swing.JTable JT, String sql) {
        try {
            RegistrarBeans cb = new RegistrarBeans();
            ResultSet rs;
            DefaultTableModel modelo = new DefaultTableModel();
            JT.setModel(modelo);
            rs = cb.consultaTabla(sql);
            ResultSetMetaData rsMd;
            rsMd = rs.getMetaData();
            int cantcolumnas = rsMd.getColumnCount();
            for (int i = 1; i <= cantcolumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (rs.next()) {
                Object[] columna = new Object[cantcolumnas];
                for (int i = 0; i < cantcolumnas; i++) {
                    columna[i] = rs.getObject(i + 1);
                }
                modelo.addRow(columna);
            }
        } catch (Exception e) {
            System.out.println("Error" + e.toString());
        }
    }

    private void cargarCliente() {
        try {
            ResultSet rs = clienteBeans.consultaTabla("SELECT cedula FROM cliente");
            while (rs.next()) {
                cbcedula.addItem(rs.getString("cedula"));
            }
        } catch (SQLException e) {
            System.out.println("Error al cargar los clientes: " + e.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btnconsultart;
    private javax.swing.JComboBox<String> cbcedula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtRegistro;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
